# yaml-language-server: $schema=https://raw.githubusercontent.com/pulumi/pulumi/master/pkg/codegen/schema/pulumi.json
---
name: aws-tailscale
resources:
  aws-tailscale:index:Bastion:
    isComponent: true
    inputProperties:
      vpcId:
        type: string
        description: "The VPC the Bastion should be created in"
      subnetIds:
        type: array
        items:
          type: string
        description: "The subnet Ids to launch instances in"
      route:
        type: string
        description: "The route you'd like to advertise via tailscale"
      region:
        type: string
        description: "The AWS region you're using"
    requiredInputs:
      - vpcId
      - subnetIds
      - route
      - region
    properties:
      asgName:
        type: string
        description: "The name of the ASG that managed the bastion instances"
    required:
      - asgName
language:
  csharp:
    packageReferences:
      Pulumi: 3.*
      Pulumi.Aws: 5.*
      Pulumi.Tailscale: 0.*
  go:
    generateResourceContainerTypes: true
    importBasePath: github.com/lbrlabs/pulumi-aws-tailscalebastion/sdk/go/bastion
  nodejs:
    dependencies:
      "@pulumi/aws": "^5.0.0"
      "@pulumi/tailscale": "^0.11.0"
    devDependencies:
      typescript: "^3.7.0"
  python:
    requires:
      pulumi: ">=3.0.0,<4.0.0"
      pulumi-aws: ">=5.0.0,<6.0.0"
      pulumi-tailscale: ">=0.0.0,<1.0.0"
